name: main-ci

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:

    name: publish-main
    runs-on: ubuntu-latest

    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for gitversion

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          useConfigFile: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore -p:Version=${{ env.GitVersion_NuGetVersion }}

      - name: Test
        run: dotnet test
        
      - name: Pack
        run: dotnet pack src/ShipitSmarter.TestHelpers/ShipitSmarter.TestHelpers.csproj  --no-build --configuration Release -p:PackageVersion=${{ env.GitVersion_NuGetVersion }}

      - name: PushNuget
        run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.SHIPITSMARTER_TESTHELPERS_NUGET_API_KEY }} --skip-duplicate

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ env.GitVersion_NuGetVersion }}
          message: 'Auto tagging version ${{ env.GitVersion_NuGetVersion }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Remove pull request versions of package
        uses: darenm/unlist-nuget@v1
        with:
          NUGET_PACKAGE: shipitsmarter.testhelpers # Full Package ID in lowercase!
          VERSION_REGEX: ^\d.\d.\d+-pullrequest.* # Regex pattern to match version
          NUGET_KEY: ${{ secrets.SHIPITSMARTER_PACKAGE_DELETER }} # nuget.org API key